name: Dev Ocean Task CI

# Dummy PR change 3
on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Read Node version from .nvmrc
        run: "echo ::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: >-
            ${{ runner.os }}-node-v${{ steps.nvm.outputs.NVMRC }}-modules-${{ hashFiles('yarn.lock')
            }}

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run CI script
        run: yarn ci
